name: "Tests"
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request:

jobs:
  Tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows, macos]

    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Go with Cache
        uses: jfrog/.github/actions/install-go-with-cache@main

      - name: Install Go Lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
        shell: bash

      - name: Test Plugins
        run: |
          for pluginDir in $(find . -maxdepth 1 -type d ! -name '.git*' | tail -n +2 | sed 's|^\./||'); do
            echo "::group::🔍$pluginDir"
              (
                cd $pluginDir
                golangci-lint run --timeout 5m --enable govet,errcheck,gosimple,ineffassign,staticcheck,typecheck,unused,gocritic,asasalint,asciicheck,errchkjson,exportloopref,forcetypeassert,makezero,nilerr,unparam,unconvert,wastedassign,usestdlibvars,gosec
                go test -v ./... -timeout 0 -race
              )
            echo "::endgroup::"
          done
        shell: bash
